root: true
parserOptions:
  parser: babel-eslint
env:
  browser: true
  node: true
extends:
- standard
- plugin:vue/recommended
plugins:
- vue
rules:
  arrow-parens: 0
  generator-star-spacing: 0
  no-console: 1